ALTER TABLE posters
MODIFY COLUMN avg_r1 DECIMAL(6,2),
MODIFY COLUMN avg_r2 DECIMAL(6,2),
MODIFY COLUMN avg_comm_r1 DECIMAL(6,2),
MODIFY COLUMN avg_comm_r2 DECIMAL(6,2),
MODIFY COLUMN avg_research_r1 DECIMAL(6,2),
MODIFY COLUMN avg_research_r2 DECIMAL(6,2),
MODIFY COLUMN avg_pres_r1 DECIMAL(6,2),
MODIFY COLUMN avg_pres_r2 DECIMAL(6,2);